# Generated by Django 3.2.8 on 2021-11-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_taskapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoScheduleTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('field', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('delta', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='DemoSchedule',
        ),
    ]
