# Generated by Django 3.2.8 on 2021-11-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulemodel',
            name='date',
            field=models.DateField(),
        ),
    ]
